language: go

sudo: false

env:
  - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9

script:
  - GOMAXPROCS=4 GORACE="halt_on_error=1" go test -race -v ./...