language: go

sudo: false

env:
  - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  # Install to build pages
  - nvm install 4


install:
  - dep ensure

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

script:
  - GOMAXPROCS=4 GORACE="halt_on_error=1" go test -race -v ./...
  - npm install docpress && ./node_modules/.bin/docpress build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi